vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
    # Selon entité mapping imagefile
       collection_image:
    #    chemin ou les photos seront uploadees
           uri_prefix: /img/collection_image
           upload_destination: '%kernel.project_dir%/public/img/collection_image'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true